format = """
${sudo}$directory$git_branch
$python$gcloud 
[>](bold cyan) """

[python]
symbol = " "

[git_branch]
symbol = " "

[gcloud]
format = 'on [$symbol${project} as $account@$domain]($style) '
